#!/usr/bin/env bash
#
# bootstrap.sh — runs ON the VM. Attached as the instance startup-script by
# provision.sh, so it also re-runs on every boot. Everything here is idempotent.
#
# Responsibilities:
#   1. Docker Engine + compose plugin from Docker's own apt repo
#   2. /opt/ak-project directory layout + .env derived from the instance metadata
#   3. the ak-project-stack.service systemd unit that brings the stack up on boot
#
# It deliberately does NOT write docker-compose.yml or the Caddyfile — deploy.sh
# ships those from the repo so there is exactly one source of truth for them.

set -euo pipefail

STACK_DIR=/opt/ak-project
STACK_USER="${SUDO_USER:-${STACK_USER:-}}"

log() { printf '[bootstrap] %s\n' "$*"; }

# --------------------------------------------------------------- 1. Docker
if ! command -v docker >/dev/null 2>&1; then
  log "installing Docker Engine"
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl gnupg rsync jq

  install -m 0755 -d /etc/apt/keyrings
  if [ ! -f /etc/apt/keyrings/docker.asc ]; then
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc
  fi

  # shellcheck disable=SC1091
  . /etc/os-release
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
https://download.docker.com/linux/ubuntu ${VERSION_CODENAME} stable" \
    > /etc/apt/sources.list.d/docker.list

  apt-get update -qq
  apt-get install -y -qq \
    docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
else
  log "Docker already present: $(docker --version)"
fi

systemctl enable --now docker

# Let the login user drive docker without sudo. On a fresh boot SUDO_USER is
# unset (startup-scripts run as root), so fall back to whoever owns a home dir.
if [ -z "$STACK_USER" ]; then
  STACK_USER="$(ls -1 /home 2>/dev/null | head -n1 || true)"
fi
if [ -n "$STACK_USER" ] && id "$STACK_USER" >/dev/null 2>&1; then
  usermod -aG docker "$STACK_USER" || true
fi

# Pre-pull the proxy image so the first `compose up` is instant and so a
# transient registry outage later cannot take TLS termination down with it.
docker pull caddy:2-alpine

# ----------------------------------------------------------- 2. stack layout
log "creating $STACK_DIR layout"
mkdir -p \
  "$STACK_DIR"/src/leads \
  "$STACK_DIR"/src/slam \
  "$STACK_DIR"/data/leads \
  "$STACK_DIR"/data/slam \
  "$STACK_DIR"/caddy/data \
  "$STACK_DIR"/caddy/config

# The app containers run as non-root; the bind-mounted data dirs must be writable.
chmod 0777 "$STACK_DIR"/data/leads "$STACK_DIR"/data/slam

# The external IP is authoritative from the metadata server, which means the
# hostnames follow the VM even if the address is ever re-reserved.
PUBLIC_IP="$(curl -fsS -H 'Metadata-Flavor: Google' \
  'http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip')"
PUBLIC_IP_DASHED="${PUBLIC_IP//./-}"

# Written every boot: it is derived state, never hand-edited. COMPOSE_PROFILES is
# preserved across reboots because deploy.sh flips it to `apps` once images exist.
EXISTING_PROFILES=""
if [ -f "$STACK_DIR/.env" ]; then
  EXISTING_PROFILES="$(grep -E '^COMPOSE_PROFILES=' "$STACK_DIR/.env" | cut -d= -f2- || true)"
fi

cat > "$STACK_DIR/.env" <<EOF
# Generated by bootstrap.sh on every boot. Do not edit by hand.
PUBLIC_IP=${PUBLIC_IP}
PUBLIC_IP_DASHED=${PUBLIC_IP_DASHED}
LEADS_HOST=leads-${PUBLIC_IP_DASHED}.nip.io
SLAM_HOST=slam-${PUBLIC_IP_DASHED}.nip.io
# Empty => only the reverse proxy starts. deploy.sh sets this to "apps" once the
# application images have actually been built, so a reboot never wedges on a
# missing image.
COMPOSE_PROFILES=${EXISTING_PROFILES}
EOF

# Operator-set values (API keys, provider switches) live in .env.local, which is
# NEVER in the repo and is not regenerated. Appending it here is what makes a
# secret survive both a reboot and the next deploy, since this file is rewritten
# from scratch every time. Keep it 0600: it holds credentials.
if [ -f "$STACK_DIR/.env.local" ]; then
  chmod 600 "$STACK_DIR/.env.local"
  printf '\n# --- appended from .env.local (operator-managed, not generated) ---\n' \
    >> "$STACK_DIR/.env"
  cat "$STACK_DIR/.env.local" >> "$STACK_DIR/.env"
  log "merged $(grep -cE '^[A-Z_]+=' "$STACK_DIR/.env.local" || echo 0) operator override(s) from .env.local"
fi
chmod 600 "$STACK_DIR/.env"

log "public IP $PUBLIC_IP -> leads-${PUBLIC_IP_DASHED}.nip.io / slam-${PUBLIC_IP_DASHED}.nip.io"

# ---------------------------------------------------------- 3. systemd unit
cat > /etc/systemd/system/ak-project-stack.service <<'EOF'
[Unit]
Description=ak-project application stack (docker compose)
Requires=docker.service
After=docker.service network-online.target
Wants=network-online.target
# Nothing to do until deploy.sh has shipped the compose file.
ConditionPathExists=/opt/ak-project/docker-compose.yml

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=/opt/ak-project
EnvironmentFile=/opt/ak-project/.env
# Re-merge operator overrides before every start. bootstrap.sh regenerates .env from
# instance metadata, but it only runs at provisioning time -- so without this a reboot
# (or a machine-type change, which is a stop/start) silently drops everything set in
# .env.local. That is how SLAM_BACKEND=real reverted to the stub twice, with the API
# still reporting healthy while serving synthetic reconstructions.
ExecStartPre=/opt/ak-project/merge-env.sh
ExecStart=/usr/bin/docker compose up -d --remove-orphans
ExecStop=/usr/bin/docker compose down
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target
EOF

# Idempotent re-merge of .env.local into .env, run by the unit before every start.
cat > "$STACK_DIR/merge-env.sh" <<'MERGE'
#!/usr/bin/env bash
# Append/replace every KEY=VALUE from .env.local into .env. Safe to run repeatedly.
set -euo pipefail
STACK_DIR=/opt/ak-project
[ -f "$STACK_DIR/.env.local" ] || exit 0
while IFS= read -r line; do
  case "$line" in ''|\#*) continue ;; esac
  key="${line%%=*}"
  [ "$key" = "$line" ] && continue
  # Drop any existing definition, then append the authoritative one.
  sed -i "/^${key}=/d" "$STACK_DIR/.env"
  printf '%s\n' "$line" >> "$STACK_DIR/.env"
done < "$STACK_DIR/.env.local"
chmod 600 "$STACK_DIR/.env"
MERGE
chmod 700 "$STACK_DIR/merge-env.sh"

systemctl daemon-reload
systemctl enable ak-project-stack.service

# Only start it if there is something to start; on first boot there is not.
if [ -f "$STACK_DIR/docker-compose.yml" ]; then
  systemctl restart ak-project-stack.service
fi

log "done"
